// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/auth/auth.proto

package authconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	auth "github.com/nnc/university-reports-creator/gen/go/proto/auth"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AuthServiceName is the fully-qualified name of the AuthService service.
	AuthServiceName = "auth.AuthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthServiceRegisterProcedure is the fully-qualified name of the AuthService's Register RPC.
	AuthServiceRegisterProcedure = "/auth.AuthService/Register"
	// AuthServiceLoginProcedure is the fully-qualified name of the AuthService's Login RPC.
	AuthServiceLoginProcedure = "/auth.AuthService/Login"
	// AuthServiceLoginWithGoogleProcedure is the fully-qualified name of the AuthService's
	// LoginWithGoogle RPC.
	AuthServiceLoginWithGoogleProcedure = "/auth.AuthService/LoginWithGoogle"
	// AuthServiceValidateTokenProcedure is the fully-qualified name of the AuthService's ValidateToken
	// RPC.
	AuthServiceValidateTokenProcedure = "/auth.AuthService/ValidateToken"
	// AuthServiceRefreshTokenProcedure is the fully-qualified name of the AuthService's RefreshToken
	// RPC.
	AuthServiceRefreshTokenProcedure = "/auth.AuthService/RefreshToken"
)

// AuthServiceClient is a client for the auth.AuthService service.
type AuthServiceClient interface {
	Register(context.Context, *connect.Request[auth.RegisterRequest]) (*connect.Response[auth.RegisterResponse], error)
	Login(context.Context, *connect.Request[auth.LoginRequest]) (*connect.Response[auth.LoginResponse], error)
	LoginWithGoogle(context.Context, *connect.Request[auth.LoginWithGoogleRequest]) (*connect.Response[auth.LoginWithGoogleResponse], error)
	ValidateToken(context.Context, *connect.Request[auth.ValidateTokenRequest]) (*connect.Response[auth.ValidateTokenResponse], error)
	RefreshToken(context.Context, *connect.Request[auth.RefreshTokenRequest]) (*connect.Response[auth.RefreshTokenResponse], error)
}

// NewAuthServiceClient constructs a client for the auth.AuthService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	authServiceMethods := auth.File_proto_auth_auth_proto.Services().ByName("AuthService").Methods()
	return &authServiceClient{
		register: connect.NewClient[auth.RegisterRequest, auth.RegisterResponse](
			httpClient,
			baseURL+AuthServiceRegisterProcedure,
			connect.WithSchema(authServiceMethods.ByName("Register")),
			connect.WithClientOptions(opts...),
		),
		login: connect.NewClient[auth.LoginRequest, auth.LoginResponse](
			httpClient,
			baseURL+AuthServiceLoginProcedure,
			connect.WithSchema(authServiceMethods.ByName("Login")),
			connect.WithClientOptions(opts...),
		),
		loginWithGoogle: connect.NewClient[auth.LoginWithGoogleRequest, auth.LoginWithGoogleResponse](
			httpClient,
			baseURL+AuthServiceLoginWithGoogleProcedure,
			connect.WithSchema(authServiceMethods.ByName("LoginWithGoogle")),
			connect.WithClientOptions(opts...),
		),
		validateToken: connect.NewClient[auth.ValidateTokenRequest, auth.ValidateTokenResponse](
			httpClient,
			baseURL+AuthServiceValidateTokenProcedure,
			connect.WithSchema(authServiceMethods.ByName("ValidateToken")),
			connect.WithClientOptions(opts...),
		),
		refreshToken: connect.NewClient[auth.RefreshTokenRequest, auth.RefreshTokenResponse](
			httpClient,
			baseURL+AuthServiceRefreshTokenProcedure,
			connect.WithSchema(authServiceMethods.ByName("RefreshToken")),
			connect.WithClientOptions(opts...),
		),
	}
}

// authServiceClient implements AuthServiceClient.
type authServiceClient struct {
	register        *connect.Client[auth.RegisterRequest, auth.RegisterResponse]
	login           *connect.Client[auth.LoginRequest, auth.LoginResponse]
	loginWithGoogle *connect.Client[auth.LoginWithGoogleRequest, auth.LoginWithGoogleResponse]
	validateToken   *connect.Client[auth.ValidateTokenRequest, auth.ValidateTokenResponse]
	refreshToken    *connect.Client[auth.RefreshTokenRequest, auth.RefreshTokenResponse]
}

// Register calls auth.AuthService.Register.
func (c *authServiceClient) Register(ctx context.Context, req *connect.Request[auth.RegisterRequest]) (*connect.Response[auth.RegisterResponse], error) {
	return c.register.CallUnary(ctx, req)
}

// Login calls auth.AuthService.Login.
func (c *authServiceClient) Login(ctx context.Context, req *connect.Request[auth.LoginRequest]) (*connect.Response[auth.LoginResponse], error) {
	return c.login.CallUnary(ctx, req)
}

// LoginWithGoogle calls auth.AuthService.LoginWithGoogle.
func (c *authServiceClient) LoginWithGoogle(ctx context.Context, req *connect.Request[auth.LoginWithGoogleRequest]) (*connect.Response[auth.LoginWithGoogleResponse], error) {
	return c.loginWithGoogle.CallUnary(ctx, req)
}

// ValidateToken calls auth.AuthService.ValidateToken.
func (c *authServiceClient) ValidateToken(ctx context.Context, req *connect.Request[auth.ValidateTokenRequest]) (*connect.Response[auth.ValidateTokenResponse], error) {
	return c.validateToken.CallUnary(ctx, req)
}

// RefreshToken calls auth.AuthService.RefreshToken.
func (c *authServiceClient) RefreshToken(ctx context.Context, req *connect.Request[auth.RefreshTokenRequest]) (*connect.Response[auth.RefreshTokenResponse], error) {
	return c.refreshToken.CallUnary(ctx, req)
}

// AuthServiceHandler is an implementation of the auth.AuthService service.
type AuthServiceHandler interface {
	Register(context.Context, *connect.Request[auth.RegisterRequest]) (*connect.Response[auth.RegisterResponse], error)
	Login(context.Context, *connect.Request[auth.LoginRequest]) (*connect.Response[auth.LoginResponse], error)
	LoginWithGoogle(context.Context, *connect.Request[auth.LoginWithGoogleRequest]) (*connect.Response[auth.LoginWithGoogleResponse], error)
	ValidateToken(context.Context, *connect.Request[auth.ValidateTokenRequest]) (*connect.Response[auth.ValidateTokenResponse], error)
	RefreshToken(context.Context, *connect.Request[auth.RefreshTokenRequest]) (*connect.Response[auth.RefreshTokenResponse], error)
}

// NewAuthServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthServiceHandler(svc AuthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authServiceMethods := auth.File_proto_auth_auth_proto.Services().ByName("AuthService").Methods()
	authServiceRegisterHandler := connect.NewUnaryHandler(
		AuthServiceRegisterProcedure,
		svc.Register,
		connect.WithSchema(authServiceMethods.ByName("Register")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceLoginHandler := connect.NewUnaryHandler(
		AuthServiceLoginProcedure,
		svc.Login,
		connect.WithSchema(authServiceMethods.ByName("Login")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceLoginWithGoogleHandler := connect.NewUnaryHandler(
		AuthServiceLoginWithGoogleProcedure,
		svc.LoginWithGoogle,
		connect.WithSchema(authServiceMethods.ByName("LoginWithGoogle")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceValidateTokenHandler := connect.NewUnaryHandler(
		AuthServiceValidateTokenProcedure,
		svc.ValidateToken,
		connect.WithSchema(authServiceMethods.ByName("ValidateToken")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceRefreshTokenHandler := connect.NewUnaryHandler(
		AuthServiceRefreshTokenProcedure,
		svc.RefreshToken,
		connect.WithSchema(authServiceMethods.ByName("RefreshToken")),
		connect.WithHandlerOptions(opts...),
	)
	return "/auth.AuthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthServiceRegisterProcedure:
			authServiceRegisterHandler.ServeHTTP(w, r)
		case AuthServiceLoginProcedure:
			authServiceLoginHandler.ServeHTTP(w, r)
		case AuthServiceLoginWithGoogleProcedure:
			authServiceLoginWithGoogleHandler.ServeHTTP(w, r)
		case AuthServiceValidateTokenProcedure:
			authServiceValidateTokenHandler.ServeHTTP(w, r)
		case AuthServiceRefreshTokenProcedure:
			authServiceRefreshTokenHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthServiceHandler struct{}

func (UnimplementedAuthServiceHandler) Register(context.Context, *connect.Request[auth.RegisterRequest]) (*connect.Response[auth.RegisterResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("auth.AuthService.Register is not implemented"))
}

func (UnimplementedAuthServiceHandler) Login(context.Context, *connect.Request[auth.LoginRequest]) (*connect.Response[auth.LoginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("auth.AuthService.Login is not implemented"))
}

func (UnimplementedAuthServiceHandler) LoginWithGoogle(context.Context, *connect.Request[auth.LoginWithGoogleRequest]) (*connect.Response[auth.LoginWithGoogleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("auth.AuthService.LoginWithGoogle is not implemented"))
}

func (UnimplementedAuthServiceHandler) ValidateToken(context.Context, *connect.Request[auth.ValidateTokenRequest]) (*connect.Response[auth.ValidateTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("auth.AuthService.ValidateToken is not implemented"))
}

func (UnimplementedAuthServiceHandler) RefreshToken(context.Context, *connect.Request[auth.RefreshTokenRequest]) (*connect.Response[auth.RefreshTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("auth.AuthService.RefreshToken is not implemented"))
}
