// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/file/file.proto

package fileconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	file "github.com/nnc/university-reports-creator/gen/go/proto/file"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// FileServiceName is the fully-qualified name of the FileService service.
	FileServiceName = "file.FileService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// FileServiceUploadProcedure is the fully-qualified name of the FileService's Upload RPC.
	FileServiceUploadProcedure = "/file.FileService/Upload"
	// FileServiceDownloadProcedure is the fully-qualified name of the FileService's Download RPC.
	FileServiceDownloadProcedure = "/file.FileService/Download"
	// FileServiceDeleteProcedure is the fully-qualified name of the FileService's Delete RPC.
	FileServiceDeleteProcedure = "/file.FileService/Delete"
	// FileServiceListProcedure is the fully-qualified name of the FileService's List RPC.
	FileServiceListProcedure = "/file.FileService/List"
)

// FileServiceClient is a client for the file.FileService service.
type FileServiceClient interface {
	Upload(context.Context, *connect.Request[file.UploadRequest]) (*connect.Response[file.UploadResponse], error)
	Download(context.Context, *connect.Request[file.DownloadRequest]) (*connect.Response[file.DownloadResponse], error)
	Delete(context.Context, *connect.Request[file.DeleteRequest]) (*connect.Response[emptypb.Empty], error)
	List(context.Context, *connect.Request[file.ListRequest]) (*connect.Response[file.ListResponse], error)
}

// NewFileServiceClient constructs a client for the file.FileService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFileServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) FileServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	fileServiceMethods := file.File_proto_file_file_proto.Services().ByName("FileService").Methods()
	return &fileServiceClient{
		upload: connect.NewClient[file.UploadRequest, file.UploadResponse](
			httpClient,
			baseURL+FileServiceUploadProcedure,
			connect.WithSchema(fileServiceMethods.ByName("Upload")),
			connect.WithClientOptions(opts...),
		),
		download: connect.NewClient[file.DownloadRequest, file.DownloadResponse](
			httpClient,
			baseURL+FileServiceDownloadProcedure,
			connect.WithSchema(fileServiceMethods.ByName("Download")),
			connect.WithClientOptions(opts...),
		),
		delete: connect.NewClient[file.DeleteRequest, emptypb.Empty](
			httpClient,
			baseURL+FileServiceDeleteProcedure,
			connect.WithSchema(fileServiceMethods.ByName("Delete")),
			connect.WithClientOptions(opts...),
		),
		list: connect.NewClient[file.ListRequest, file.ListResponse](
			httpClient,
			baseURL+FileServiceListProcedure,
			connect.WithSchema(fileServiceMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
	}
}

// fileServiceClient implements FileServiceClient.
type fileServiceClient struct {
	upload   *connect.Client[file.UploadRequest, file.UploadResponse]
	download *connect.Client[file.DownloadRequest, file.DownloadResponse]
	delete   *connect.Client[file.DeleteRequest, emptypb.Empty]
	list     *connect.Client[file.ListRequest, file.ListResponse]
}

// Upload calls file.FileService.Upload.
func (c *fileServiceClient) Upload(ctx context.Context, req *connect.Request[file.UploadRequest]) (*connect.Response[file.UploadResponse], error) {
	return c.upload.CallUnary(ctx, req)
}

// Download calls file.FileService.Download.
func (c *fileServiceClient) Download(ctx context.Context, req *connect.Request[file.DownloadRequest]) (*connect.Response[file.DownloadResponse], error) {
	return c.download.CallUnary(ctx, req)
}

// Delete calls file.FileService.Delete.
func (c *fileServiceClient) Delete(ctx context.Context, req *connect.Request[file.DeleteRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.delete.CallUnary(ctx, req)
}

// List calls file.FileService.List.
func (c *fileServiceClient) List(ctx context.Context, req *connect.Request[file.ListRequest]) (*connect.Response[file.ListResponse], error) {
	return c.list.CallUnary(ctx, req)
}

// FileServiceHandler is an implementation of the file.FileService service.
type FileServiceHandler interface {
	Upload(context.Context, *connect.Request[file.UploadRequest]) (*connect.Response[file.UploadResponse], error)
	Download(context.Context, *connect.Request[file.DownloadRequest]) (*connect.Response[file.DownloadResponse], error)
	Delete(context.Context, *connect.Request[file.DeleteRequest]) (*connect.Response[emptypb.Empty], error)
	List(context.Context, *connect.Request[file.ListRequest]) (*connect.Response[file.ListResponse], error)
}

// NewFileServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFileServiceHandler(svc FileServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	fileServiceMethods := file.File_proto_file_file_proto.Services().ByName("FileService").Methods()
	fileServiceUploadHandler := connect.NewUnaryHandler(
		FileServiceUploadProcedure,
		svc.Upload,
		connect.WithSchema(fileServiceMethods.ByName("Upload")),
		connect.WithHandlerOptions(opts...),
	)
	fileServiceDownloadHandler := connect.NewUnaryHandler(
		FileServiceDownloadProcedure,
		svc.Download,
		connect.WithSchema(fileServiceMethods.ByName("Download")),
		connect.WithHandlerOptions(opts...),
	)
	fileServiceDeleteHandler := connect.NewUnaryHandler(
		FileServiceDeleteProcedure,
		svc.Delete,
		connect.WithSchema(fileServiceMethods.ByName("Delete")),
		connect.WithHandlerOptions(opts...),
	)
	fileServiceListHandler := connect.NewUnaryHandler(
		FileServiceListProcedure,
		svc.List,
		connect.WithSchema(fileServiceMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	return "/file.FileService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FileServiceUploadProcedure:
			fileServiceUploadHandler.ServeHTTP(w, r)
		case FileServiceDownloadProcedure:
			fileServiceDownloadHandler.ServeHTTP(w, r)
		case FileServiceDeleteProcedure:
			fileServiceDeleteHandler.ServeHTTP(w, r)
		case FileServiceListProcedure:
			fileServiceListHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFileServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedFileServiceHandler struct{}

func (UnimplementedFileServiceHandler) Upload(context.Context, *connect.Request[file.UploadRequest]) (*connect.Response[file.UploadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("file.FileService.Upload is not implemented"))
}

func (UnimplementedFileServiceHandler) Download(context.Context, *connect.Request[file.DownloadRequest]) (*connect.Response[file.DownloadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("file.FileService.Download is not implemented"))
}

func (UnimplementedFileServiceHandler) Delete(context.Context, *connect.Request[file.DeleteRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("file.FileService.Delete is not implemented"))
}

func (UnimplementedFileServiceHandler) List(context.Context, *connect.Request[file.ListRequest]) (*connect.Response[file.ListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("file.FileService.List is not implemented"))
}
