// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/template/template.proto

package templateconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	template "github.com/nnc/university-reports-creator/gen/go/proto/template"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TemplateServiceName is the fully-qualified name of the TemplateService service.
	TemplateServiceName = "template.TemplateService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TemplateServiceCreateTemplateProcedure is the fully-qualified name of the TemplateService's
	// CreateTemplate RPC.
	TemplateServiceCreateTemplateProcedure = "/template.TemplateService/CreateTemplate"
	// TemplateServiceGetTemplateProcedure is the fully-qualified name of the TemplateService's
	// GetTemplate RPC.
	TemplateServiceGetTemplateProcedure = "/template.TemplateService/GetTemplate"
	// TemplateServiceListTemplatesProcedure is the fully-qualified name of the TemplateService's
	// ListTemplates RPC.
	TemplateServiceListTemplatesProcedure = "/template.TemplateService/ListTemplates"
	// TemplateServiceUpdateTemplateProcedure is the fully-qualified name of the TemplateService's
	// UpdateTemplate RPC.
	TemplateServiceUpdateTemplateProcedure = "/template.TemplateService/UpdateTemplate"
	// TemplateServiceDeleteTemplateProcedure is the fully-qualified name of the TemplateService's
	// DeleteTemplate RPC.
	TemplateServiceDeleteTemplateProcedure = "/template.TemplateService/DeleteTemplate"
)

// TemplateServiceClient is a client for the template.TemplateService service.
type TemplateServiceClient interface {
	CreateTemplate(context.Context, *connect.Request[template.CreateTemplateRequest]) (*connect.Response[template.TemplateResponse], error)
	GetTemplate(context.Context, *connect.Request[template.GetTemplateRequest]) (*connect.Response[template.TemplateResponse], error)
	ListTemplates(context.Context, *connect.Request[template.ListTemplatesRequest]) (*connect.Response[template.ListTemplatesResponse], error)
	UpdateTemplate(context.Context, *connect.Request[template.UpdateTemplateRequest]) (*connect.Response[template.TemplateResponse], error)
	DeleteTemplate(context.Context, *connect.Request[template.DeleteTemplateRequest]) (*connect.Response[template.DeleteTemplateResponse], error)
}

// NewTemplateServiceClient constructs a client for the template.TemplateService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTemplateServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TemplateServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	templateServiceMethods := template.File_proto_template_template_proto.Services().ByName("TemplateService").Methods()
	return &templateServiceClient{
		createTemplate: connect.NewClient[template.CreateTemplateRequest, template.TemplateResponse](
			httpClient,
			baseURL+TemplateServiceCreateTemplateProcedure,
			connect.WithSchema(templateServiceMethods.ByName("CreateTemplate")),
			connect.WithClientOptions(opts...),
		),
		getTemplate: connect.NewClient[template.GetTemplateRequest, template.TemplateResponse](
			httpClient,
			baseURL+TemplateServiceGetTemplateProcedure,
			connect.WithSchema(templateServiceMethods.ByName("GetTemplate")),
			connect.WithClientOptions(opts...),
		),
		listTemplates: connect.NewClient[template.ListTemplatesRequest, template.ListTemplatesResponse](
			httpClient,
			baseURL+TemplateServiceListTemplatesProcedure,
			connect.WithSchema(templateServiceMethods.ByName("ListTemplates")),
			connect.WithClientOptions(opts...),
		),
		updateTemplate: connect.NewClient[template.UpdateTemplateRequest, template.TemplateResponse](
			httpClient,
			baseURL+TemplateServiceUpdateTemplateProcedure,
			connect.WithSchema(templateServiceMethods.ByName("UpdateTemplate")),
			connect.WithClientOptions(opts...),
		),
		deleteTemplate: connect.NewClient[template.DeleteTemplateRequest, template.DeleteTemplateResponse](
			httpClient,
			baseURL+TemplateServiceDeleteTemplateProcedure,
			connect.WithSchema(templateServiceMethods.ByName("DeleteTemplate")),
			connect.WithClientOptions(opts...),
		),
	}
}

// templateServiceClient implements TemplateServiceClient.
type templateServiceClient struct {
	createTemplate *connect.Client[template.CreateTemplateRequest, template.TemplateResponse]
	getTemplate    *connect.Client[template.GetTemplateRequest, template.TemplateResponse]
	listTemplates  *connect.Client[template.ListTemplatesRequest, template.ListTemplatesResponse]
	updateTemplate *connect.Client[template.UpdateTemplateRequest, template.TemplateResponse]
	deleteTemplate *connect.Client[template.DeleteTemplateRequest, template.DeleteTemplateResponse]
}

// CreateTemplate calls template.TemplateService.CreateTemplate.
func (c *templateServiceClient) CreateTemplate(ctx context.Context, req *connect.Request[template.CreateTemplateRequest]) (*connect.Response[template.TemplateResponse], error) {
	return c.createTemplate.CallUnary(ctx, req)
}

// GetTemplate calls template.TemplateService.GetTemplate.
func (c *templateServiceClient) GetTemplate(ctx context.Context, req *connect.Request[template.GetTemplateRequest]) (*connect.Response[template.TemplateResponse], error) {
	return c.getTemplate.CallUnary(ctx, req)
}

// ListTemplates calls template.TemplateService.ListTemplates.
func (c *templateServiceClient) ListTemplates(ctx context.Context, req *connect.Request[template.ListTemplatesRequest]) (*connect.Response[template.ListTemplatesResponse], error) {
	return c.listTemplates.CallUnary(ctx, req)
}

// UpdateTemplate calls template.TemplateService.UpdateTemplate.
func (c *templateServiceClient) UpdateTemplate(ctx context.Context, req *connect.Request[template.UpdateTemplateRequest]) (*connect.Response[template.TemplateResponse], error) {
	return c.updateTemplate.CallUnary(ctx, req)
}

// DeleteTemplate calls template.TemplateService.DeleteTemplate.
func (c *templateServiceClient) DeleteTemplate(ctx context.Context, req *connect.Request[template.DeleteTemplateRequest]) (*connect.Response[template.DeleteTemplateResponse], error) {
	return c.deleteTemplate.CallUnary(ctx, req)
}

// TemplateServiceHandler is an implementation of the template.TemplateService service.
type TemplateServiceHandler interface {
	CreateTemplate(context.Context, *connect.Request[template.CreateTemplateRequest]) (*connect.Response[template.TemplateResponse], error)
	GetTemplate(context.Context, *connect.Request[template.GetTemplateRequest]) (*connect.Response[template.TemplateResponse], error)
	ListTemplates(context.Context, *connect.Request[template.ListTemplatesRequest]) (*connect.Response[template.ListTemplatesResponse], error)
	UpdateTemplate(context.Context, *connect.Request[template.UpdateTemplateRequest]) (*connect.Response[template.TemplateResponse], error)
	DeleteTemplate(context.Context, *connect.Request[template.DeleteTemplateRequest]) (*connect.Response[template.DeleteTemplateResponse], error)
}

// NewTemplateServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTemplateServiceHandler(svc TemplateServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	templateServiceMethods := template.File_proto_template_template_proto.Services().ByName("TemplateService").Methods()
	templateServiceCreateTemplateHandler := connect.NewUnaryHandler(
		TemplateServiceCreateTemplateProcedure,
		svc.CreateTemplate,
		connect.WithSchema(templateServiceMethods.ByName("CreateTemplate")),
		connect.WithHandlerOptions(opts...),
	)
	templateServiceGetTemplateHandler := connect.NewUnaryHandler(
		TemplateServiceGetTemplateProcedure,
		svc.GetTemplate,
		connect.WithSchema(templateServiceMethods.ByName("GetTemplate")),
		connect.WithHandlerOptions(opts...),
	)
	templateServiceListTemplatesHandler := connect.NewUnaryHandler(
		TemplateServiceListTemplatesProcedure,
		svc.ListTemplates,
		connect.WithSchema(templateServiceMethods.ByName("ListTemplates")),
		connect.WithHandlerOptions(opts...),
	)
	templateServiceUpdateTemplateHandler := connect.NewUnaryHandler(
		TemplateServiceUpdateTemplateProcedure,
		svc.UpdateTemplate,
		connect.WithSchema(templateServiceMethods.ByName("UpdateTemplate")),
		connect.WithHandlerOptions(opts...),
	)
	templateServiceDeleteTemplateHandler := connect.NewUnaryHandler(
		TemplateServiceDeleteTemplateProcedure,
		svc.DeleteTemplate,
		connect.WithSchema(templateServiceMethods.ByName("DeleteTemplate")),
		connect.WithHandlerOptions(opts...),
	)
	return "/template.TemplateService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TemplateServiceCreateTemplateProcedure:
			templateServiceCreateTemplateHandler.ServeHTTP(w, r)
		case TemplateServiceGetTemplateProcedure:
			templateServiceGetTemplateHandler.ServeHTTP(w, r)
		case TemplateServiceListTemplatesProcedure:
			templateServiceListTemplatesHandler.ServeHTTP(w, r)
		case TemplateServiceUpdateTemplateProcedure:
			templateServiceUpdateTemplateHandler.ServeHTTP(w, r)
		case TemplateServiceDeleteTemplateProcedure:
			templateServiceDeleteTemplateHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTemplateServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTemplateServiceHandler struct{}

func (UnimplementedTemplateServiceHandler) CreateTemplate(context.Context, *connect.Request[template.CreateTemplateRequest]) (*connect.Response[template.TemplateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("template.TemplateService.CreateTemplate is not implemented"))
}

func (UnimplementedTemplateServiceHandler) GetTemplate(context.Context, *connect.Request[template.GetTemplateRequest]) (*connect.Response[template.TemplateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("template.TemplateService.GetTemplate is not implemented"))
}

func (UnimplementedTemplateServiceHandler) ListTemplates(context.Context, *connect.Request[template.ListTemplatesRequest]) (*connect.Response[template.ListTemplatesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("template.TemplateService.ListTemplates is not implemented"))
}

func (UnimplementedTemplateServiceHandler) UpdateTemplate(context.Context, *connect.Request[template.UpdateTemplateRequest]) (*connect.Response[template.TemplateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("template.TemplateService.UpdateTemplate is not implemented"))
}

func (UnimplementedTemplateServiceHandler) DeleteTemplate(context.Context, *connect.Request[template.DeleteTemplateRequest]) (*connect.Response[template.DeleteTemplateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("template.TemplateService.DeleteTemplate is not implemented"))
}
