apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: university-reports

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - service-auth.yaml
  - service-document.yaml
  - service-files.yaml
  - service-gateway.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: university-reports-creator
  app.kubernetes.io/part-of: university-reports