// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/document/document.proto

package documentconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	document "github.com/nnc/university-reports-creator/gen/go/proto/document"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DocumentServiceName is the fully-qualified name of the DocumentService service.
	DocumentServiceName = "document.DocumentService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DocumentServiceCreateDocumentProcedure is the fully-qualified name of the DocumentService's
	// CreateDocument RPC.
	DocumentServiceCreateDocumentProcedure = "/document.DocumentService/CreateDocument"
	// DocumentServiceGetDocumentProcedure is the fully-qualified name of the DocumentService's
	// GetDocument RPC.
	DocumentServiceGetDocumentProcedure = "/document.DocumentService/GetDocument"
	// DocumentServiceListDocumentsProcedure is the fully-qualified name of the DocumentService's
	// ListDocuments RPC.
	DocumentServiceListDocumentsProcedure = "/document.DocumentService/ListDocuments"
	// DocumentServiceUpdateDocumentProcedure is the fully-qualified name of the DocumentService's
	// UpdateDocument RPC.
	DocumentServiceUpdateDocumentProcedure = "/document.DocumentService/UpdateDocument"
	// DocumentServiceDeleteDocumentProcedure is the fully-qualified name of the DocumentService's
	// DeleteDocument RPC.
	DocumentServiceDeleteDocumentProcedure = "/document.DocumentService/DeleteDocument"
)

// DocumentServiceClient is a client for the document.DocumentService service.
type DocumentServiceClient interface {
	CreateDocument(context.Context, *connect.Request[document.CreateDocumentRequest]) (*connect.Response[document.DocumentResponse], error)
	GetDocument(context.Context, *connect.Request[document.GetDocumentRequest]) (*connect.Response[document.DocumentResponse], error)
	ListDocuments(context.Context, *connect.Request[document.ListDocumentsRequest]) (*connect.Response[document.ListDocumentsResponse], error)
	UpdateDocument(context.Context, *connect.Request[document.UpdateDocumentRequest]) (*connect.Response[document.DocumentResponse], error)
	DeleteDocument(context.Context, *connect.Request[document.DeleteDocumentRequest]) (*connect.Response[document.DeleteDocumentResponse], error)
}

// NewDocumentServiceClient constructs a client for the document.DocumentService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDocumentServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DocumentServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	documentServiceMethods := document.File_proto_document_document_proto.Services().ByName("DocumentService").Methods()
	return &documentServiceClient{
		createDocument: connect.NewClient[document.CreateDocumentRequest, document.DocumentResponse](
			httpClient,
			baseURL+DocumentServiceCreateDocumentProcedure,
			connect.WithSchema(documentServiceMethods.ByName("CreateDocument")),
			connect.WithClientOptions(opts...),
		),
		getDocument: connect.NewClient[document.GetDocumentRequest, document.DocumentResponse](
			httpClient,
			baseURL+DocumentServiceGetDocumentProcedure,
			connect.WithSchema(documentServiceMethods.ByName("GetDocument")),
			connect.WithClientOptions(opts...),
		),
		listDocuments: connect.NewClient[document.ListDocumentsRequest, document.ListDocumentsResponse](
			httpClient,
			baseURL+DocumentServiceListDocumentsProcedure,
			connect.WithSchema(documentServiceMethods.ByName("ListDocuments")),
			connect.WithClientOptions(opts...),
		),
		updateDocument: connect.NewClient[document.UpdateDocumentRequest, document.DocumentResponse](
			httpClient,
			baseURL+DocumentServiceUpdateDocumentProcedure,
			connect.WithSchema(documentServiceMethods.ByName("UpdateDocument")),
			connect.WithClientOptions(opts...),
		),
		deleteDocument: connect.NewClient[document.DeleteDocumentRequest, document.DeleteDocumentResponse](
			httpClient,
			baseURL+DocumentServiceDeleteDocumentProcedure,
			connect.WithSchema(documentServiceMethods.ByName("DeleteDocument")),
			connect.WithClientOptions(opts...),
		),
	}
}

// documentServiceClient implements DocumentServiceClient.
type documentServiceClient struct {
	createDocument *connect.Client[document.CreateDocumentRequest, document.DocumentResponse]
	getDocument    *connect.Client[document.GetDocumentRequest, document.DocumentResponse]
	listDocuments  *connect.Client[document.ListDocumentsRequest, document.ListDocumentsResponse]
	updateDocument *connect.Client[document.UpdateDocumentRequest, document.DocumentResponse]
	deleteDocument *connect.Client[document.DeleteDocumentRequest, document.DeleteDocumentResponse]
}

// CreateDocument calls document.DocumentService.CreateDocument.
func (c *documentServiceClient) CreateDocument(ctx context.Context, req *connect.Request[document.CreateDocumentRequest]) (*connect.Response[document.DocumentResponse], error) {
	return c.createDocument.CallUnary(ctx, req)
}

// GetDocument calls document.DocumentService.GetDocument.
func (c *documentServiceClient) GetDocument(ctx context.Context, req *connect.Request[document.GetDocumentRequest]) (*connect.Response[document.DocumentResponse], error) {
	return c.getDocument.CallUnary(ctx, req)
}

// ListDocuments calls document.DocumentService.ListDocuments.
func (c *documentServiceClient) ListDocuments(ctx context.Context, req *connect.Request[document.ListDocumentsRequest]) (*connect.Response[document.ListDocumentsResponse], error) {
	return c.listDocuments.CallUnary(ctx, req)
}

// UpdateDocument calls document.DocumentService.UpdateDocument.
func (c *documentServiceClient) UpdateDocument(ctx context.Context, req *connect.Request[document.UpdateDocumentRequest]) (*connect.Response[document.DocumentResponse], error) {
	return c.updateDocument.CallUnary(ctx, req)
}

// DeleteDocument calls document.DocumentService.DeleteDocument.
func (c *documentServiceClient) DeleteDocument(ctx context.Context, req *connect.Request[document.DeleteDocumentRequest]) (*connect.Response[document.DeleteDocumentResponse], error) {
	return c.deleteDocument.CallUnary(ctx, req)
}

// DocumentServiceHandler is an implementation of the document.DocumentService service.
type DocumentServiceHandler interface {
	CreateDocument(context.Context, *connect.Request[document.CreateDocumentRequest]) (*connect.Response[document.DocumentResponse], error)
	GetDocument(context.Context, *connect.Request[document.GetDocumentRequest]) (*connect.Response[document.DocumentResponse], error)
	ListDocuments(context.Context, *connect.Request[document.ListDocumentsRequest]) (*connect.Response[document.ListDocumentsResponse], error)
	UpdateDocument(context.Context, *connect.Request[document.UpdateDocumentRequest]) (*connect.Response[document.DocumentResponse], error)
	DeleteDocument(context.Context, *connect.Request[document.DeleteDocumentRequest]) (*connect.Response[document.DeleteDocumentResponse], error)
}

// NewDocumentServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDocumentServiceHandler(svc DocumentServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	documentServiceMethods := document.File_proto_document_document_proto.Services().ByName("DocumentService").Methods()
	documentServiceCreateDocumentHandler := connect.NewUnaryHandler(
		DocumentServiceCreateDocumentProcedure,
		svc.CreateDocument,
		connect.WithSchema(documentServiceMethods.ByName("CreateDocument")),
		connect.WithHandlerOptions(opts...),
	)
	documentServiceGetDocumentHandler := connect.NewUnaryHandler(
		DocumentServiceGetDocumentProcedure,
		svc.GetDocument,
		connect.WithSchema(documentServiceMethods.ByName("GetDocument")),
		connect.WithHandlerOptions(opts...),
	)
	documentServiceListDocumentsHandler := connect.NewUnaryHandler(
		DocumentServiceListDocumentsProcedure,
		svc.ListDocuments,
		connect.WithSchema(documentServiceMethods.ByName("ListDocuments")),
		connect.WithHandlerOptions(opts...),
	)
	documentServiceUpdateDocumentHandler := connect.NewUnaryHandler(
		DocumentServiceUpdateDocumentProcedure,
		svc.UpdateDocument,
		connect.WithSchema(documentServiceMethods.ByName("UpdateDocument")),
		connect.WithHandlerOptions(opts...),
	)
	documentServiceDeleteDocumentHandler := connect.NewUnaryHandler(
		DocumentServiceDeleteDocumentProcedure,
		svc.DeleteDocument,
		connect.WithSchema(documentServiceMethods.ByName("DeleteDocument")),
		connect.WithHandlerOptions(opts...),
	)
	return "/document.DocumentService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DocumentServiceCreateDocumentProcedure:
			documentServiceCreateDocumentHandler.ServeHTTP(w, r)
		case DocumentServiceGetDocumentProcedure:
			documentServiceGetDocumentHandler.ServeHTTP(w, r)
		case DocumentServiceListDocumentsProcedure:
			documentServiceListDocumentsHandler.ServeHTTP(w, r)
		case DocumentServiceUpdateDocumentProcedure:
			documentServiceUpdateDocumentHandler.ServeHTTP(w, r)
		case DocumentServiceDeleteDocumentProcedure:
			documentServiceDeleteDocumentHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDocumentServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDocumentServiceHandler struct{}

func (UnimplementedDocumentServiceHandler) CreateDocument(context.Context, *connect.Request[document.CreateDocumentRequest]) (*connect.Response[document.DocumentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("document.DocumentService.CreateDocument is not implemented"))
}

func (UnimplementedDocumentServiceHandler) GetDocument(context.Context, *connect.Request[document.GetDocumentRequest]) (*connect.Response[document.DocumentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("document.DocumentService.GetDocument is not implemented"))
}

func (UnimplementedDocumentServiceHandler) ListDocuments(context.Context, *connect.Request[document.ListDocumentsRequest]) (*connect.Response[document.ListDocumentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("document.DocumentService.ListDocuments is not implemented"))
}

func (UnimplementedDocumentServiceHandler) UpdateDocument(context.Context, *connect.Request[document.UpdateDocumentRequest]) (*connect.Response[document.DocumentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("document.DocumentService.UpdateDocument is not implemented"))
}

func (UnimplementedDocumentServiceHandler) DeleteDocument(context.Context, *connect.Request[document.DeleteDocumentRequest]) (*connect.Response[document.DeleteDocumentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("document.DocumentService.DeleteDocument is not implemented"))
}
